# Generated by Django 5.2.1 on 2025-05-23 19:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinhospital',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 5, 23))]),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinhospital',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 5, 23))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 5, 23))]),
        ),
    ]
